name: subtitle
description: ->
  A library that makes it easy to work with multiple subtitle/caption file formats,
  written with highly efficient code, highly customizable (90%), supports Null Safety.
version: 0.1.0-beta.2
homepage: https://github.com/dsc-uob/subtitle
issue_tracker: https://github.com/dsc-uob/subtitle/issues
documentation: https://github.com/dsc-uob/subtitle/wiki

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  path: ">=1.8.3 <1.9.0"
  universal_io: ">=2.2.2 <2.3.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
